Main/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(r'^arbitra_see$', views.arbitra_see, name='arbitra_see'),
    url(r'^arbitra_altera$', views.arbitra_altera, name='arbitra_altera'),
    url(r'^arbitra_remove$', views.arbitra_remove, name='arbitra_remove'),
    url(r'^partida$', views.partida, name='partida'),
    url(r'^', views.index, name='index'),
    url(r'^pdf2go',views.pdf2go, name='pdf2go')
]

TokyoBD/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import view
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Main.urls')),
]

Main/models.py
from django.db import models

# Create your models here.
class HabilitadoArbitrar(models.Model):

    def __str__(self):
        return self.codigo

    codigo = models.IntegerField() 
    esporte= models.CharField(max_length=30)

Main/forms.py
from django import forms
from .models import HabilitadoArbitrar
class HabilitadoForm(forms.ModelForm):
    class Meta:
        model = HabilitadoArbitrar
        fields =('codigo','esporte',)

Main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.template import Context
from Main.forms import HabilitadoForm
import cx_Oracle
import re
# Create your views here.
def pdf2go(request):
    #Retrieve data or whatever you need
    return render_to_pdf(
            'Main/partida.html',
            {
                'pagesize':'A4',
                'mylist': results,
            }
        )
def index(request):
    template = loader.get_template('Main/index.html')
    context={}
    return HttpResponse(template.render(context,request))

def arbitra_see(request):
    ip='grad.icmc.usp.br'
    port= 15215
    SID='orcl'
    dsn_tns= cx_Oracle.makedsn(ip, port, SID)
    con= cx_Oracle.connect('8058718','a',dsn_tns) 
    cur= con.cursor()
    cur.execute('select HabilitadoArbitrar.NumeroId,Nome,Esporte from HabilitadoArbitrar join Arbitro on HabilitadoArbitrar.NumeroId= Arbitro.NumeroId order by Nome')
    data=[]
    for a in cur:
        datatem=[]
        datatem.append(a[0])
        datatem.append(a[1])
        datatem.append(a[2])
        data.append(datatem)
    template = loader.get_template('Main/consulta.html')
    context ={'data': data}
    return HttpResponse(template.render(context,request))

def arbitra_altera(request):
    try:
        ip='grad.icmc.usp.br'
        port= 15215
        SID='orcl'
        dsn_tns= cx_Oracle.makedsn(ip, port, SID)
        con= cx_Oracle.connect('8058718','a',dsn_tns) 
        cur= con.cursor()
        if request.method =='GET' :
            form= HabilitadoForm()
        else: 
            form = HabilitadoForm(request.POST)
            if form.is_valid():
                context ={'form':form,} 
                aux=form.cleaned_data
                aux_codigo=str(aux['codigo'])
                aux_esporte=((aux['esporte']))
                aux_esporte= re.sub('[\"]','[\']',aux_esporte)
                statement='insert into HabilitadoArbitrar(NumeroId,Esporte) values ('+ aux_codigo +','+'\''+aux_esporte+'\''+')'
                cur.execute(statement)
                con.commit()

        cur.execute('select HabilitadoArbitrar.NumeroId,Nome,Esporte from HabilitadoArbitrar join Arbitro on HabilitadoArbitrar.NumeroId= Arbitro.NumeroId order by Nome')
        data=[]
        for a in cur:
            datatem=[]
            datatem.append(a[0])
            datatem.append(a[1])
            datatem.append(a[2])
            data.append(datatem)
    
    except(RuntimeError, TypeError, NameError):
        pass
    template = loader.get_template('Main/altera.html')
    context ={'form':form,'data':data,}
    return HttpResponse(template.render(context,request))
def partida(request):
    return HttpResponse()

def arbitra_remove(request):
    ip='grad.icmc.usp.br'
    port= 15215
    SID='orcl'
    dsn_tns= cx_Oracle.makedsn(ip, port, SID)
    con= cx_Oracle.connect('8058718','a',dsn_tns) 
    cur= con.cursor()
    if request.method =='GET' :
        form= HabilitadoForm()
    else: 
        form = HabilitadoForm(request.POST)
        if form.is_valid():
            context ={'form':form,} 
            aux=form.cleaned_data
            aux_codigo=str(aux['codigo'])
            aux_esporte=((aux['esporte']))
            aux_esporte= re.sub('[\"]','[\']',aux_esporte)
            statement='delete from HabilitadoArbitrar where NumeroId='+aux_codigo+'and Esporte='+'\''+aux_esporte+'\''
            cur.execute(statement)
            con.commit()

    cur.execute('select HabilitadoArbitrar.NumeroId,Nome,Esporte from HabilitadoArbitrar join Arbitro on HabilitadoArbitrar.NumeroId= Arbitro.NumeroId order by Nome')
    data=[]
    for a in cur:
        datatem=[]
        datatem.append(a[0])
        datatem.append(a[1])
        datatem.append(a[2])
        data.append(datatem)
    template = loader.get_template('Main/remove.html')
    context ={'form':form,'data':data,}
    return HttpResponse(template.render(context,request))
def partida(request):
    ip='grad.icmc.usp.br'
    port= 15215
    SID='orcl'
    dsn_tns= cx_Oracle.makedsn(ip, port, SID)
    con= cx_Oracle.connect('8058718','a',dsn_tns) 
    cur= con.cursor()
    cur.execute(' SELECT DISTINCT ATLETA.NOME,COUNT(*) FROM ATLETA JOIN ATLETAPARTICIPA ON ATLETA.NUMEROID=ATLETAPARTICIPA.NUMEROID JOIN EQUIPEJOGA ON EQUIPEJOGA.NUMEROEQUIPE = ATLETAPARTICIPA.NUMERO GROUP BY ATLETA.NOME HAVING COUNT(*)>3 ')
    data=[]
    for a in cur:
        datatem=[]
        datatem.append(a[0])
        datatem.append(a[1])
        data.append(datatem)
    template = loader.get_template('Main/partida.html')
    print(con.version)
    context ={'data': data}
    return HttpResponse(template.render(context,request))

Main/templates/Main/altera.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Tokyo 2020 - Database</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static "css/materialize.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  </head>
  <body>
    <header>
      <nav class="blue darken-2" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="{% url 'index' %}" class="brand-logo">Tokyo 2020</a>
          <ul class="right hide-on-med-and-down">
            <li><a class='dropdown-button ' data-activates='dropdown1' href="#">Habilitado a Arbitrar</a>
              <ul id='dropdown1' class='dropdown-content'>
                <li class="white"><a href="{% url 'arbitra_see' %}" class="light-green-text text-darken-2">Consulta</a></li>
                <li class="white"><a href="{% url 'arbitra_altera' %}" class="light-green-text text-darken-2">Adiciona</a></li>
                <li class="white"><a href="{% url 'arbitra_remove' %}" class="light-green-text text-darken-2">Remove</a></li>
              </ul> 
            </li>

          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="{% url 'arbitra_see' %}">Ver Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_altera' %}">Adiciona Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_remove' %}">Remove Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="#">Navbar Link</a></li>
          </ul>

          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
      </nav>
    </header>
    <main>

      <div class="container">
        <form action="arbitra_altera" method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col s12">
              <div class="row">
                {{ form }}
                <button class="btn waves-effect waves-light push-s4 col s4 " type="submit" name="action">Submit
                  <i class="material-icons right">send</i>
                </div>
              </button>
            </div>
          </div>
        </main>
        <footer class="page-footer light-green darken-2">
          <div class="container">
            <div class="row">
              <div class="col l3 s12">
                <h5 class="white-text">Resources</h5>
              </div>
            </div>
            <div class="row">
              <ul>
                <div class="col l3 s12">
                  <li><a class="white-text" href="https://www.oracle.com/index.html">Oracle Database</a></li>
                </div>
                <div class="col l3 s12">
                  <li><a class="white-text" href="https://www.djangoproject.com/">Django</a></li>
                </div>
                <div class="col l3 s12">
                  <li><a class="white-text" href="http://materializecss.com/">Materialize</a></li>
                </div>
                <div class="col l3 s12">
                  <li><a class="white-text" href="https://www.python.org/">Python</a></li>
                </div>
              </ul>
            </div>
          </div>


          </div>
          <div class="footer-copyright">
            <div class="container">
              <div class="row">
                <div class="col s3 ">
                  Pedro Morello Abbud 
                </div>
                <div class="col s3 ">
                  Danilo Barbosa Porto
                </div>
                <div class="col s3 ">
                  Gustavo Rocha Spena
                </div>
                <div class="col s3 ">
                  Xoel Lopez Barata 
                </div>
              </div>
            </div>
          </div>

        </footer>

        <!--  Scripts-->

      </script>
      <script src="{% static "js/materialize.js" %}"></script>
      <script src="{% static "js/init.js" %}"></script>
      <script>
        var id={}  ;
var esporte={};
{% for a in data %}
id["{{ a.0 }}"]=null;
esporte["{{ a.2 }}"]=null;
{% endfor %}
      </script>
      <script>
        $(document).ready(function() {
          $('id_codigo').autocomplete({
            data:id
          });
          $('#id_esporte').autocomplete({
            data:esporte
          });

      });</script>
  </body>
</html>

Main/templates/Main/consulta.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Tokyo 2020 - Database</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static "css/materialize.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  </head>
  <body>
    <header>
      <nav class="blue darken-2" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="{% url 'index' %}" class="brand-logo">Tokyo 2020</a>
          <ul class="right hide-on-med-and-down">
            <li><a class='dropdown-button ' data-activates='dropdown1' href="#">Habilitado a Arbitrar</a>
              <ul id='dropdown1' class='dropdown-content'>
                <li class="white"><a href="{% url 'arbitra_see' %}" class="light-green-text text-darken-2">Consulta</a></li>
                <li class="white"><a href="{% url 'arbitra_altera' %}" class="light-green-text text-darken-2">Adiciona</a></li>
                <li class="white"><a href="{% url 'arbitra_remove' %}" class="light-green-text text-darken-2">Remove</a></li>
              </ul> 
            </li>

          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="{% url 'arbitra_see' %}">Ver Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_altera' %}">Adiciona Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_remove' %}">Remove Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="#">Navbar Link</a></li>
          </ul>

          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
      </nav>
    </header>
    <main>

      <div class="container">
        {% if data %}
        <table class="highlight">
          <thead>
            <tr>
              <th data-field="id">Id</th>
              <th data-field="name">Nome</th>
              <th data-field="esporte">Esporte</th>
            </tr>
          </thead>
          <tbody>
            {% for i in data%}
            <tr>
              <td> {{ i.0}}</td>
              <td> {{ i.1}}</td>
              <td> {{ i.2}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% endif %}
      </div>
    </main>
    <footer class="page-footer light-green darken-2">
          <div class="container">
            <div class="row">
              <div class="col l3 s12">
                <h5 class="white-text">Resources</h5>
              </div>
            </div>
            <div class="row">
              <ul>
                <div class="col l3 s12">
                  <li><a class="white-text" href="https://www.oracle.com/index.html">Oracle Database</a></li>
                </div>
                <div class="col l3 s12">
                  <li><a class="white-text" href="https://www.djangoproject.com/">Django</a></li>
                </div>
                <div class="col l3 s12">
                  <li><a class="white-text" href="http://materializecss.com/">Materialize</a></li>
                </div>
                <div class="col l3 s12">
                  <li><a class="white-text" href="https://www.python.org/">Python</a></li>
                </div>
              </ul>
            </div>
          </div>

            <div class="footer-copyright">
        <div class="container">
          <div class="row">
            <div class="col s3 ">
              Pedro Morello Abbud 
            </div>
            <div class="col s3 ">
              Danilo Barbosa Porto
            </div>
            <div class="col s3 ">
              Gustavo Rocha Spena
            </div>
            <div class="col s3 ">
              Xoel Lopez Barata 
            </div>
          </div>
        </div>
      </div>

    </footer>


    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static "js/materialize.js" %}"></script>
    <script src="{% static "js/init.js" %}"></script>


</body>
</html>

Main/templates/Main/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Tokyo 2020 - Database</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static "css/materialize.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  </head>
  <body>
    <header>
      <nav class="blue darken-2" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="{% url 'index' %}" class="brand-logo">Tokyo 2020</a>
          <ul class="right hide-on-med-and-down">
            <li><a class='dropdown-button ' data-activates='dropdown1' href="#">Habilitado a Arbitrar</a>
              <ul id='dropdown1' class='dropdown-content'>
                <li class="white"><a href="{% url 'arbitra_see' %}" class="light-green-text text-darken-2">Consulta</a></li>
                <li class="white"><a href="{% url 'arbitra_altera' %}" class="light-green-text text-darken-2">Adiciona</a></li>
                <li class="white"><a href="{% url 'arbitra_remove' %}" class="light-green-text text-darken-2">Remove</a></li>
              </ul> 
            </li>

          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="{% url 'arbitra_see' %}">Ver Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_altera' %}">Adiciona Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_remove' %}">Remove Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="#">Navbar Link</a></li>
          </ul>

          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
      </nav>
    </header>
    <main>

      <div class="container">
        {% if data %}
        <table class="highlight">
          <thead>
            <tr>
              <th data-field="id">Id</th>
              <th data-field="name">Nome</th>
              <th data-field="esporte">Esporte</th>
            </tr>
          </thead>
          <tbody>
            {% for i in data%}
            <tr>
              <td> {{ i.0}}</td>
              <td> {{ i.1}}</td>
              <td> {{ i.2}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% endif %}
      </div>
    </main>
    <footer class="page-footer light-green darken-2">
          <div class="container">
            <div class="row">
              <div class="col l3 s12">
                <h5 class="white-text">Resources</h5>
              </div>
            </div>
            <div class="row">
              <ul>
                <div class="col l3 s12">
                  <li><a class="white-text" href="https://www.oracle.com/index.html">Oracle Database</a></li>
                </div>
                <div class="col l3 s12">
                  <li><a class="white-text" href="https://www.djangoproject.com/">Django</a></li>
                </div>
                <div class="col l3 s12">
                  <li><a class="white-text" href="http://materializecss.com/">Materialize</a></li>
                </div>
                <div class="col l3 s12">
                  <li><a class="white-text" href="https://www.python.org/">Python</a></li>
                </div>
              </ul>
            </div>
          </div>


           <div class="footer-copyright">
        <div class="container">
          <div class="row">
            <div class="col s3 ">
              Pedro Morello Abbud 
            </div>
            <div class="col s3 ">
              Danilo Barbosa Porto
            </div>
            <div class="col s3 ">
              Gustavo Rocha Spena
            </div>
            <div class="col s3 ">
              Xoel Lopez Barata 
            </div>
          </div>
        </div>
      </div>

    </footer>


    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static "js/materialize.js" %}"></script>
    <script src="{% static "js/init.js" %}"></script>


</body>
</html>

Main/templates/Main/partida.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Tokyo 2020 - Database</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static "css/materialize.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  </head>
  <body>
    <header>
      <nav class="blue darken-2" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="{% url 'index' %}" class="brand-logo">Tokyo 2020</a>
          <ul class="right hide-on-med-and-down">
            <li><a class='dropdown-button ' data-activates='dropdown1' href="#">Habilitado a Arbitrar</a>
              <ul id='dropdown1' class='dropdown-content'>
                <li class="white"><a href="{% url 'arbitra_see' %}" class="light-green-text text-darken-2">Consulta</a></li>
                <li class="white"><a href="{% url 'arbitra_altera' %}" class="light-green-text text-darken-2">Adiciona</a></li>
                <li class="white"><a href="{% url 'arbitra_remove' %}" class="light-green-text text-darken-2">Remove</a></li>
              </ul> 
            </li>

          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="{% url 'arbitra_see' %}">Ver Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_altera' %}">Adiciona Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_remove' %}">Remove Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>
          <ul class="right hide-on-med-and-down">

            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="{% url 'arbitra_see' %}">Navbar Link</a></li>
          </ul>

          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
      </nav>
    </header>
    <main>

      <div class="container">
        {% if data %}
        <table class="highlight">
          <thead>
            <tr>
              <th data-field="nome">Nome</th>
              <th data-field="name">Numero Jogos</th>
            </tr>
          </thead>
          <tbody>
            {% for i in data%}
            <tr>
              <td> {{ i.0}}</td>
              <td> {{ i.1}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% endif %}
        <form action="{% url 'pdf2go' %}" method="GET">
          {% csrf_token %}
          <button id="submit" class="waves-effect waves-light btn" value="Click" onclick="2pdf()" >button</a>
        </form>

      </div>
    </main>
    <footer class="page-footer light-green darken-2">
      <div class="container">
        <div class="row">
          <div class="col l3 s12">
            <h5 class="white-text">Resources</h5>
          </div>
        </div>
          <div class="row">
            <ul>
              <div class="col l3 s12">
                <li><a class="white-text" href="https://www.oracle.com/index.html">Oracle Database</a></li>
              </div>
              <div class="col l3 s12">
                <li><a class="white-text" href="https://www.djangoproject.com/">Django</a></li>
              </div>
              <div class="col l3 s12">
                <li><a class="white-text" href="http://materializecss.com/">Materialize</a></li>
              </div>
              <div class="col l3 s12">
                <li><a class="white-text" href="https://www.python.org/">Python</a></li>
              </div>
            </ul>
          </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          <div class="row">
            <div class="col s3 ">
              Pedro Morello Abbud 
            </div>
            <div class="col s3 ">
              Danilo Barbosa Porto
            </div>
            <div class="col s3 ">
              Gustavo Rocha Spena
            </div>
            <div class="col s3 ">
              Xoel Lopez Barata 
            </div>
          </div>
        </div>
      </div>

    </footer>


    <!--  Scripts-->

    <script>
      function 2pdf(){
        var xhr = new XMLHttpRequest();
        xhr.open('GET', "{% url 'pdf2go' %}", true);
        xhr.send();
      }
    </script>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static "js/materialize.js" %}"></script>
    <script src="{% static "js/init.js" %}"></script>


  </body>
</html>

Main/templates/Main/remove.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Tokyo 2020 - Database</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static "css/materialize.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  </head>
  <body>
    <header>
      <nav class="blue darken-2" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="{% url 'index' %}" class="brand-logo">Tokyo 2020</a>
          <ul class="right hide-on-med-and-down">
            <li><a class='dropdown-button ' data-activates='dropdown1' href="#">Habilitado a Arbitrar</a>
              <ul id='dropdown1' class='dropdown-content'>
                <li class="white"><a href="{% url 'arbitra_see' %}" class="light-green-text text-darken-2">Consulta</a></li>
                <li class="white"><a href="{% url 'arbitra_altera' %}" class="light-green-text text-darken-2">Adiciona</a></li>
                <li class="white"><a href="{% url 'arbitra_remove' %}" class="light-green-text text-darken-2">Remove</a></li>
              </ul> 
            </li>

          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="{% url 'arbitra_see' %}">Ver Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_altera' %}">Adiciona Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'arbitra_remove' %}">Remove Habilitado a Arbitrar</a></li>
            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'partida' %}">Partida</a></li>
          </ul>

          <ul id="nav-mobile" class="side-nav">
            <li><a href="#">Navbar Link</a></li>
          </ul>

          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
      </nav>
    </header>
    <main>

      <div class="container">
        <form action="arbitra_remove" method="post">
          {% csrf_token %}
        <div class="row">
          <div class="col s12">
            <div class="row">
              {{ form }}
                <button class="btn waves-effect waves-light push-s4 col s4 " type="submit" name="action">Submit
                  <i class="material-icons right">send</i>
                </div>
            </button>
          </div>
        </div>
      </main>
      <footer class="page-footer light-green darken-2">
        <div class="container">
          <div class="row">
            <div class="col l3 s12">
              <h5 class="white-text">Resources</h5>
            </div>
          </div>
          <div class="row">
            <ul>
              <div class="col l3 s12">
                <li><a class="white-text" href="https://www.oracle.com/index.html">Oracle Database</a></li>
              </div>
              <div class="col l3 s12">
                <li><a class="white-text" href="https://www.djangoproject.com/">Django</a></li>
              </div>
              <div class="col l3 s12">
                <li><a class="white-text" href="http://materializecss.com/">Materialize</a></li>
              </div>
              <div class="col l3 s12">
                <li><a class="white-text" href="https://www.python.org/">Python</a></li>
              </div>
            </ul>
          </div>

        </div>
        <div class="footer-copyright">
          <div class="container">
            <div class="row">
              <div class="col s3 ">
                Pedro Morello Abbud 
              </div>
              <div class="col s3 ">
                Danilo Barbosa Porto
              </div>
              <div class="col s3 ">
                Gustavo Rocha Spena
              </div>
              <div class="col s3 ">
                Xoel Lopez Barata 
              </div>
            </div>
          </div>
        </div>

      </footer>

      <!--  Scripts-->

    </script>
    <script src="{% static "js/materialize.js" %}"></script>
    <script src="{% static "js/init.js" %}"></script>
    <script>
      var id={}  ;
var esporte={};
{% for a in data %}
id["{{ a.0 }}"]=null;
esporte["{{ a.2 }}"]=null;
{% endfor %}
    </script>
    <script>
      $(document).ready(function() {
        $('#id_codigo').autocomplete({
          data:id
        });
        $('#id_esporte').autocomplete({
          data:esporte
        });

    });</script>
</body>
</html>